### ISSUE TITLE
fcvt.s.d instruction not working with SSR

### ISSUE THREAD

**Issue by gioelegott** [pulp-platform/snitch_cluster#116]
Conversion from double to single precision (fcvt.s.d) isn't working when used in combination with ssr. It hangs indefinitely on verilator but works on banshee.
This small test demonstrates the issue.
[test_fcvt.zip](https://github.com/pulp-platform/snitch_cluster/files/14590858/test_fcvt.zip)

**Comment by and-ivanov** [comment]
This seems to be more difficult to reproduce in the latest version (https://github.com/pulp-platform/snitch_cluster/commit/11d053489df24fd6057b5d985f6aa389cd507fed). Simulation is hanging only **sometimes** (may require multiple reruns) when built with multithreaded support
```
VLT_FLAGS='--threads 16' VLT_COBJ=work-vlt/vlt/verilated_threads.o VLT_CFLAGS=-DVL_THREADED \
    make -C target/snitch_cluster bin/snitch_cluster.vlt
```

**Comment by colluca** [comment]
This seems to be solved by https://github.com/pulp-platform/snitch_cluster/pull/158.
