### ISSUE TITLE
Docker container image failing after make command

### ISSUE THREAD

**Issue by RedDuality** [pulp-platform/snitch_cluster#118]
Following the tutorial, after building the docker container on the repo folder, the make command crashes.
![Screenshot 2024-03-15 145812](https://github.com/pulp-platform/snitch_cluster/assets/61973885/cc2ee345-6f97-48d3-b673-56ac54094a59)

**Comment by colluca** [comment]
This was due to the `common_cells` dependency, which was updated upstream. The issue is now fixed on main after merging https://github.com/pulp-platform/snitch_cluster/pull/119.
