### ISSUE TITLE
Need login for nonfree part

### ISSUE THREAD

**Issue by franktaTian** [pulp-platform/snitch_cluster#129]
Hi,
I cloned this repo.  and try  : make 
This will  checkout a nofree submodule   first, but need username and password.
Any help?

**Comment by colluca** [comment]
Hi @franktaTian,

The `make all` target in the root of the directory is not needed if you do not intend to use the nonfree repository. Please have a look at the [Getting Started guide] for the instructions you might be interested in.

Cheers,
Luca
