### ISSUE TITLE
Add +define+COMMON_CELLS_ASSERTS_OFF

### ISSUE THREAD

**Issue by franktaTian** [pulp-platform/snitch_cluster#130]
Please  add +define+COMMON_CELLS_ASSERTS_OFF in target/common/common.mk 

Env.  docker (main)
Run.  
cd /repo/target/snitch_cluster
make bin/snitch_cluster.vlt
Will report error ifndef  COMMON_CELLS_ASSERTS_OFF for common cells.

**Comment by colluca** [comment]
Hi @franktaTian, do you mean what this line here is doing?

https://github.com/pulp-platform/snitch_cluster/blob/13d1e6b3aaa8e53d5b39858c6ee871b186bf9aa2/target/common/common.mk#L73

**Comment by franktaTian** [comment]
I added "VLT_FLAGS    += +define+COMMON_CELLS_ASSERTS_OFF" in this file

> Hi @franktaTian, do you mean what this line here is doing?
> 
> https://github.com/pulp-platform/snitch_cluster/blob/13d1e6b3aaa8e53d5b39858c6ee871b186bf9aa2/target/common/common.mk#L73

**Comment by colluca** [comment]
The line I quoted adds exactly the flag you mentioned to the flags in `work-vlt/files`, and this file is passed in the invocation of the `verilator` command (see `-f` option).

Also, the commands you mention are reproduced by the CI and they did not log any errors on the last run.

I will close this issue. Feel free to reopen if you have other details.
