### ISSUE TITLE
Incorrect description of `ICACHE_ENABLE_REGISTER` in Snitch cluster peripherals

### ISSUE THREAD

**Issue by colluca** [pulp-platform/snitch_cluster#18]
https://github.com/pulp-platform/snitch/blob/670517084e234cfa1cd941aaf2710e1ee5b34adc/hw/ip/snitch_cluster/src/snitch_cluster_peripheral/snitch_cluster_peripheral_reg.hjson#L394-L405

**Comment by paulsc96** [comment]
Addressed in #22.
