### ISSUE TITLE
confusion of ModuleNotFoundError

### ISSUE THREAD

**Issue by itcastcastcast** [pulp-platform/snitch_cluster#181]
Dear Mr. Colluca,

When I try your latest version, I encounter issues such as "ModuleNotFoundError: No module named 'snitch' "and other missing library function problems. This is the output from the shell when I run the command sudo docker run -it --rm -v ~/cpp/snitch_cluster:/work -w /work/target/snitch_cluster ghcr.io/pulp-platform/snitch_cluster:main make bin/snitch_cluster.vlt, which I have recorded in out.log.
[out.log](https://github.com/user-attachments/files/16615614/out.log)

**Comment by colluca** [comment]
Yes, indeed you have to locally install the package by running `pip install -e .`. Will update tutorial instructions as soon as possible.
