### ISSUE TITLE
snRuntime: Mutexes might be uninitialized

### ISSUE THREAD

**Issue by huettern** [pulp-platform/snitch_cluster#19]
`crt0` currently doesn't init the `.bss` section. A mutex placed in `.bss` (e.g. `clint_mutex` in interrupt.c) is therefore in an uninitialized state leading to deadlocks. A fix to this should also conform to multi-cluster systems which are not participating in the cluster-wide barrier at the end of `crt0`.

**Comment by paulsc96** [comment]
@colluca Does this issue still apply? I don't see `start.S` initializing `.bss`; maybe a define-guarded init as for thread and cluster could be done.

**Comment by colluca** [comment]
> @colluca Does this issue still apply? I don't see `start.S` initializing `.bss`; maybe a define-guarded init as for thread and cluster could be done.

@paulsc96  This shouldn't apply anymore. BSS section is initialized here: https://github.com/pulp-platform/snitch_cluster/blob/b5016fe6272e980fffa7166bc9c75c9fa436f22d/sw/snRuntime/src/start.c#L45-L56
