### ISSUE TITLE
docs don't mention compiling and installing musl

### ISSUE THREAD

**Issue by JosseVanDelm** [pulp-platform/snitch_cluster#35]
Hi, I really like the documentation for this project.

However, the documentation does not seem to mention the "Build MUSL dependency" step which is executed in the CI:
```yaml
      - name: Build MUSL dependency
        run: |
          cd sw/deps
          mkdir install
          cd musl
          CC=$LLVM_BINROOT/clang ./configure --disable-shared \
          --prefix=../install/ --enable-wrapper=all \
          CFLAGS="-mcpu=snitch -menable-experimental-extensions"
          make -j4
          make install
          cd ../../../
      - name: Build Software
        run: |
          make -C target/snitch_cluster sw
```

**Comment by colluca** [comment]
Hi Josse,
Thanks for your feedback!
We are currently in the process of updating our musl implementation, after which no manual installation steps will be required.

**Comment by colluca** [comment]
#26 was recently merged to main and addresses this issue.
