### ISSUE TITLE
Verilator testbench: time is always 0 in DASM and perf results

### ISSUE THREAD

**Issue by Raragyay** [pulp-platform/snitch_cluster#57]
I am currently following the tutorial for snitch cluster at https://pulp-platform.github.io/snitch_cluster/ug/tutorial.html and reached the debugging/benchmarking step. However, when trying to analyze the performance, it seems that the `tstart` and `tend` metrics are always 0. This value persists from the DASM file to the text, csv, and json results from the other steps for benchmarking. 

![image](https://github.com/pulp-platform/snitch_cluster/assets/29154557/8a125aeb-d650-4599-bf9e-e6919caa8dd5)

The command I ran: `bin/snitch_cluster.vlt sw/apps/blas/axpy/build/axpy.elf`
Resulting files is attached.
[trace_hart_00000000.dasm.txt](https://github.com/pulp-platform/snitch_cluster/files/13043772/trace_hart_00000000.dasm.txt)
[hart_00000000_perf.json](https://github.com/pulp-platform/snitch_cluster/files/13043779/hart_00000000_perf.json)
[perf.csv](https://github.com/pulp-platform/snitch_cluster/files/13043802/perf.csv)
[event.csv](https://github.com/pulp-platform/snitch_cluster/files/13043803/event.csv)

Running on docker on Linux, amd64: 
```bash
$ uname -a
Linux b0f761a4bb94 6.5.0-1004-oem #4-Ubuntu SMP PREEMPT_DYNAMIC Fri Sep 15 19:52:30 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

Tested running on
- axpy in tutorial
- blas/axpy from repo

Things I tried changing:
- Adding back the patch from https://github.com/pulp-platform/snitch/blob/d026f47843f0ea6c269244c4e6851e0e09141ec3/util/patches/riscv-isa-sim/fesrv.patch

**Comment by colluca** [comment]
Thank you for opening the issue.

This is a known problem with Verilator simulation as it does not log simulation timestamps.
The Python scripts could be extended to use the cycle count instead of the absolute timestamp as a workaround.

If you could provide such a feature, I would be willing to merge it.

**Comment by Raragyay** [comment]
Do you know if there are any known simulators that are able to provide wall time statistics? I saw that Banshee was another tool mentioned but that seemed to lean towards instruction accuracy instead of cycle accuracy. On IIS there seemed to be other tools like Questa too.

**Comment by Raragyay** [comment]
How can one get this license? Is it offered within the Docker installation?
