### ISSUE TITLE
Support Verilator 5

### ISSUE THREAD

**Issue by RickLuiken** [pulp-platform/snitch_cluster#75]
Following from the [discussion in the fork from KU Leuven](https://github.com/KULeuven-MICAS/snitch_cluster/issues/65). I would like to have support for Verilator 5. Verilator 5 has better performance, support for timing constructs and support for assertions. It would also allow projects using the snitch cluster to use verilator 5. I think in general it would be useful to support more recent versions of tools, as this makes the upgrading process later down the line a lot easier (make small steps instead of big ones).

Upgrading to verilator 5 would involve the following steps:
- Add the `-no-timing` flag to the current tests, which disables the new timing features in verilator 5
- Add `verilated_threads.o` to the verilator build targets **OR** compile both the systemverilog and cpp sources using verilator, so verilator can manage which verilator files should be included

If you have any questions or comments, please let me know!

**Comment by colluca** [comment]
Dear @RickLuiken,

If you could provide a PR for this feature targeting Verilator 5.006, it would be well accepted and we would be willing to review and merge it.

Unfortunately we do not have enough resources to implement this feature ourselves at the moment.

**Comment by RickLuiken** [comment]
Great, I will provide the PR after the christmas break!

**Comment by colluca** [comment]
This is currently undergoing testing in https://github.com/pulp-platform/snitch_cluster/pull/158.

**Comment by colluca** [comment]
Merged in https://github.com/pulp-platform/snitch_cluster/pull/158.
